### PR TITLE
Property for the switch background color

### PR DESCRIPTION
**Pull request by Darkkrye**
Hi, I've downloaded your lib because I've found it really nice.
But when I've started to use it, I've found something missing.

## What I've found:
I have found that it is impossible to just change the switch background color. When you use the "backgroundColor" property nothing happen and the background still stay in white.

## What I've done :
- I have created an IBDesignable property called "backColor" to allows user to change the switch background color.
- I also have created a new test function to be sure the code I've written works.

Added test for the property.

### CODE REVIEW

**Comment by T-Pham** [comment]
Cool! Thanks, @Darkkrye. I will make some minor update and release a new version with this included.

**Comment by Darkkrye** [comment]
Ok. Glad to have helped :)

**Comment by T-Pham** [comment]
@Darkkrye just wanted to updating you that `backColor` is included in v2.0.1.

**Comment by Darkkrye** [comment]
Nice ! Thanx a lot ! :)

**Pull request merged**
